name: Auto-Generate Changelog

on:
  push:
    branches:
      - main

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
          pull-requests: false
          issues: false
          future-release: Unreleased

      - name: Commit changelog
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add CHANGELOG.md
          git commit -m "📦 Updated CHANGELOG.md [auto]"
          git push
